### ISSUE TITLE
WebSocket protocol error

### ISSUE THREAD

**Issue by alazymeme** [pajbot/tweet-provider#10]
Since being rate limited, I've had to start using the tweet-provider option for tweet streaming on pajbot. I'm running into a weird issue where after a while, I run into many websocket protocol errors and it just stops working. I'm forced to restart the twitter provider in order to get it working again: https://hastebin.com/ucayororek.css

Not sure if this is something I've done wrong, or if it's something wrong with tweet-provider.

**Comment by ldesgoui** [comment]
Any logs in pajbot?
It seems like it is failing and closing the TCP connection a few moments after being started

**Comment by alazymeme** [comment]
> Any logs in pajbot?
> It seems like it is failing and closing the TCP connection a few moments after being started

It's working just fine now (has been the entire day). Will send something tomorrow if it happens overnight.

**Comment by alazymeme** [comment]
This hasn't screwed up since, I'm closing and will reopen later if the issues start up again.

**Comment by alazymeme** [comment]
Reopening because I'm having the issue again

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/85193536-dbfd2000-b30c-11ea-8bea-1d96de15f0d2.png)

**Comment by RAnders00** [comment]
again, as before, are there logs of the relevant pajbot instances?

**Comment by alazymeme** [comment]
> again, as before, are there logs of the relevant pajbot instances?

Here's some errors I found: https://hastebin.com/tukucemuda.rb

**Comment by alazymeme** [comment]
btw this was fixed last night by simply restarting the tweet-provider instance

**Comment by alazymeme** [comment]
I don't get it, this only seems to happen when one of my bots follows donald trump on twitter? I'm still getting the websocket protocol errors, but it seems to be working just fine? I don't understand why I keep having issues with it

**Comment by RAnders00** [comment]
@alazymeme show us the pajbot logs of the same time frame as the errors in the tweet-provider logs. There should be at least something like `Connected to tweet-provider` or `Disconnected from tweet-provider: <something>` in the logs.

**Comment by alazymeme** [comment]
There's this, but I believe it's around the time that I restarted twitter-provider. Otherwise most of it is flooded with donaldtrump tweets
```
Jun 22 14:08:50 MainServer pajbot@fabzeef[12518]: [2020-06-22 14:08:50,729] [INFO   ] Disconnected from tweet-provider: connection was closed uncleanly (peer dropped the TCP connection without previous WebSocket closing handshake)
Jun 22 14:08:50 MainServer pajbot@fabzeef[12518]: [2020-06-22 14:08:50,729] [DEBUG  ] Connection lost to PBTwitterManager: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionLost'>: Connection to the other side was lost in a non-clean fashion.
Jun 22 14:08:50 MainServer pajbot@fabzeef[12518]: ]
Jun 22 14:08:53 MainServer pajbot@fabzeef[12518]: [2020-06-22 14:08:53,709] [INFO   ] Connected to tweet-provider
Jun 22 14:08:55 MainServer pajbot@fabzeef[12518]: [2020-06-22 14:08:55,230] [DEBUG  ] Unhandled message from tweet-provider: {'type': 'ack_subscriptions', 'data': [55386535, 2189912750, 566662738, 3083978626, 3314891286, 25073877, 353780675, 948316544349736962]}

**Comment by alazymeme** [comment]
I'm not sure if there are any log files, but above is the output I got from journalctl

**Comment by RAnders00** [comment]
You got no logs in the time frame of those repeated disconnects?

You can combine the logs using `journalctl -e -u pajbot@streamer tweet-provider`

**Comment by alazymeme** [comment]
`New connection from 12.0.0.1:42880`
`Error processing websocket for 127.0.0.1:42880: WebSocket protocol error`
`New connection from 127.0.0.1:42960`
`Error processing websocket for 127.0.0.1:42960: WebSocket protocol error`

These are the only errors I could find amongst the dt tweets. Unless it is being sourced from another bot (which I don't think would matter since they're all being hosted on the same server, right?)

**Comment by alazymeme** [comment]
Same thing on my own bot, just a slightly different port

**Comment by alazymeme** [comment]
randers helped me a little in twitch chat....closing for now

**Comment by alazymeme** [comment]
Running into this issue again:
```
Jul 26 02:44:47 MainServer tweet-provider[17906]: 2020-07-26 02:44:47,044 INFO  [tweet_provider::twitter] got a tweet from ALazyMeme: "@CallofDuty WHY BOTHER GIVING ME THE OPTION TO LIMIT MY FPS IF IT DOESN\'T FUCKING WORK ANYWAY????? ht
Jul 26 02:45:02 MainServer tweet-provider[17906]: 2020-07-26 02:45:02,841 INFO  [tweet_provider::websocket] new connection from 127.0.0.1:47164
Jul 26 02:45:03 MainServer tweet-provider[17906]: 2020-07-26 02:45:03,025 ERROR [tweet_provider::websocket] error processing websocket for 127.0.0.1:47164: WebSocket protocol error: Connection reset without closing handshake
Jul 26 02:45:31 MainServer tweet-provider[17906]: 2020-07-26 02:45:31,485 INFO  [tweet_provider::websocket] new connection from 127.0.0.1:47192
Jul 26 02:45:31 MainServer tweet-provider[17906]: 2020-07-26 02:45:31,666 ERROR [tweet_provider::websocket] error processing websocket for 127.0.0.1:47192: WebSocket protocol error: Connection reset without closing handshake
Jul 26 02:45:57 MainServer tweet-provider[17906]: 2020-07-26 02:45:57,236 INFO  [tweet_provider::websocket] new connection from 127.0.0.1:47216
Jul 26 02:45:57 MainServer tweet-provider[17906]: 2020-07-26 02:45:57,417 ERROR [tweet_provider::websocket] error processing websocket for 127.0.0.1:47216: WebSocket protocol error: Connection reset without closing handshake
```

**Comment by alazymeme** [comment]
Not only the above error, but whenever someone is mentioned in a tweet, it's not posted or anything. This might have something to do with the recent api changes?

**Comment by alazymeme** [comment]
For reference

These are the tweets:
![image](https://user-images.githubusercontent.com/12804673/88469187-e759f180-cf31-11ea-9a86-dbefac4bca57.png)

This is what was outputted in chat:
![image](https://user-images.githubusercontent.com/12804673/88469191-fe004880-cf31-11ea-92a5-79c2cd7f8f68.png)

**Comment by alazymeme** [comment]
When you add a . before the mention, it will display just fine:

![image](https://user-images.githubusercontent.com/12804673/88470111-e8901c00-cf3b-11ea-95fd-e11a4c9b54cb.png)

This is what I see:
![image](https://user-images.githubusercontent.com/12804673/88470115-efb72a00-cf3b-11ea-9038-e67ce951f4ee.png)

**Comment by pajlada** [comment]
> Not only the above error, but whenever someone is mentioned in a tweet, it's not posted or anything. This might have something to do with the recent api changes?

This is intended, and has been this way all the way since the original implementation in pajbot1
