### ISSUE TITLE
tweet-provider should restart on unfollow

### ISSUE THREAD

**Issue by alazymeme** [pajbot/tweet-provider#13]
Currently tweet-provider restarts when you follow a user, but doesn't restart when you unfollow a user. It should restart when you unfollow a user, else it will continue to fetch all activity relating to that user.

**Comment by ldesgoui** [comment]
I don't think it should, restarting incurs a considerable downtime (a few seconds), it is avoided as much as possible for that reason. We can add some messages to manually manage and restart. Issues like #14 should be tackled for what they are, not what they could be.

**Comment by alazymeme** [comment]
> I don't think it should, restarting incurs a considerable downtime (a few seconds), it is avoided as much as possible for that reason. We can add some messages to manually manage and restart. Issues like #14 should be tackled for what they are, not what they could be.

Unrelated from #14 - I still think it should restart. Why should the bot track tweets that aren't even relevant to the streamer anymore?

**Comment by ldesgoui** [comment]
It doesn't, they should be discarded when received, it's possible for this to have no runtime cost, so it ought to be developed that way. Once again, restarting incurs a considerable downtime, which should be avoided at all costs.
