### ISSUE TITLE
Large volumes of tweets silently crashes tweet provider

### ISSUE THREAD

**Issue by alazymeme** [pajbot/tweet-provider#14]
So this issue really only happens if you're following donald trump - and as a result, I can't test with any other user on twitter.
It appears that due to trump receiving such a large volume of tweets, tweet provider crashes or disconnects and stops working. If someone can find a similar twitter user, I can do more testing, but when I unfollowed trump on fabzeef's bot, the crashing stopped.

**Comment by alazymeme** [comment]
fyi I'm testing this by following a large amount of users on twitter:
https://i.alazymeme.com/LiquidGreatImage.png

https://en.wikipedia.org/wiki/List_of_most-followed_Twitter_accounts - I'm up to #32

**Comment by alazymeme** [comment]
Up to 37 now, have added a few extras on the side: https://i.alazymeme.com/AcuteElderlyImage.png

**Comment by ldesgoui** [comment]
Could you give me IDs of those users in order to test?

**Comment by alazymeme** [comment]
> Could you give me IDs of those users in text form in order to test?

I'm so confused...I can't even reproduce with this many users. It only seems to happen with trump? Which makes no fucking sense.

**Comment by alazymeme** [comment]
Need to do more testing on this. It didn't crash overnight last night, but I followed trump again in the morning and it crashed throughout the day. Could it be possible that it's something specifically to do with his account?

**Comment by ldesgoui** [comment]
Please try #15 via this build https://github.com/pajbot/tweet-provider/actions/runs/147358717

**Comment by ldesgoui** [comment]
This should also be addressed, I may look at it later today https://github.com/pajbot/tweet-provider/blob/92c0ef69506d47492b3f007eef12bbb32d057c3b/src/main.rs#L69
