### ISSUE TITLE
Properly handle Websocket close frames

### ISSUE THREAD

**Issue by ldesgoui** [pajbot/tweet-provider#6]
Right now, we ignore Close frames sent by the client, this is not in accordance with the RFC which requires an acknowledge Close frame be sent after one is received.
Our error handling also shortcuts to exiting the function, which prevents us from sending appropriate Close frames to clients.

https://tools.ietf.org/html/rfc6455#section-5.5.1

**Comment by pajlada** [comment]
@ldesgoui By "Early exists on our end still aren't handled properly" you mean if we CTRL+C the application, we don't send close frames properly to all connections but just abruptly close then?

**Comment by ldesgoui** [comment]
Yes
